import "./globals.css";
import 'remixicon/fonts/remixicon.css';


import ContextProvider from "@/components/ContextProvider";
import NavBar from "@/components/main/navbar/NavBar";
import Footer from "@/components/main/footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className="pt-20">
        <ContextProvider>
          <NavBar></NavBar>
            {children}
          <Footer></Footer>
        </ContextProvider>
      </body>
    </html>
  );
}
