import "./globals.css";
import NavBar from "@/components/main/navbar/module.NavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className="pt-20">
        <NavBar></NavBar>
        {children}
      </body>
    </html>
  );
}
